---
name: Build
on:
  push:
    branches:
      - main
      - staging
      - trying
      - "renovate/**"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        zookeeper: [3.9.2, 3.8.4, 3.7.2]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: rustup default ${{ matrix.rust }}
      - run: wget -O zookeeper.tar.gz https://dlcdn.apache.org/zookeeper/zookeeper-${{ matrix.zookeeper }}/apache-zookeeper-${{ matrix.zookeeper }}-bin.tar.gz
      - run: mkdir zookeeper
      - run: tar -zxvf zookeeper.tar.gz -C zookeeper --strip-components 1
      - run: ./scripts/ci-start-zookeeper
      - run: cargo test
