---
name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        zookeeper: [3.8.1, 3.7.1, 3.6.4, 3.5.10, 3.4.14]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: rustup default ${{ matrix.rust }}
      - run: wget -O zookeeper.tar.gz http://archive.apache.org/dist/zookeeper/zookeeper-${{ matrix.zookeeper }}/zookeeper-${{ matrix.zookeeper }}.tar.gz
      - run: mkdir zookeeper
      - run: tar -zxvf zookeeper.tar.gz -C zookeeper --strip-components 1
      - run: ./travis/before_script.sh
      - run: cargo test
